### ISSUE TITLE
X-Achse: Datum steigt nicht regelmässig

### ISSUE THREAD

**Issue by tamberg** [rsalzer/COVID_19_KT_ZH#1]
Hallo, die 1. Visualisierung in [0] zeigt 13.03. und dann direkt 16.03. was den Graph verfälscht.

Bzw. allgemein fehlen Daten auf der X-Achse für die es keine Werte gibt.

[0] https://rsalzer.github.io/COVID_19_KT_ZH/

**Comment by zdavatz** [comment]
@tamberg Kannst Du einen PR senden bitte mit einem Fix? Just do it.

**Comment by rsalzer** [comment]
Wenns nicht Balken wäre, wäre es einfacher. Dann könnte man die vorhandenen Daten per Linie verbinden und es würde nicht den Graph zerreissen ... einverstanden.

**Comment by rsalzer** [comment]
Ok, ich habe nun eine Line-Chart eingebaut, bei welchem man auch die fehlenden Tage in der X-Achse sieht.
