### ISSUE TITLE
Alter auf Y-Achse spiegeln?

### ISSUE THREAD

**Issue by tamberg** [rsalzer/COVID_19_KT_ZH#2]
Hallo, macht es bei der Darstellung nach Altersgruppen eventuell Sinn, die jüngste Gruppe unten zu haben, und die älteste zuoberst? Dann würde die Y-Achse das Alter anzeigen. (Und ev. sogar nach Gender splitten?) Wie z.B. hier https://static-secure.guim.co.uk/sys-images/Guardian/Pix/pictures/2009/10/21/1256142869661/Population-graphic-002.jpg

**Comment by rsalzer** [comment]
Das würde Sinn machen, ja. Das Problem an den Gender/Altersdaten ist momentan vor allem, dass dazu seit über einer Woche die Daten nicht aktualisiert wurden ...
