### ISSUE TITLE
Splines vs. Genauigkeit?

### ISSUE THREAD

**Issue by tamberg** [rsalzer/COVID_19_KT_ZH#3]
Hallo @rsalzer, viele der Graphen scheinen Splines zu nutzen (oder was ähnliches). Wird dadurch nicht eine Genauigkeit vorgegaukelt, die es in den Daten so nicht gibt? Wäre es eventuell genauer, einfach gerade Verbimdungen anzuzeigen, zwischen zwei Punkten? (kenne die Fachbegriffe dafür nicht).

**Comment by rsalzer** [comment]
Ja, das ist eine Interpolation, die bei chartjs standard ist. Bei der Schweiz-Sicht habe ich das bereits abgeschwächt, siehe https://rsalzer.github.io/COVID_19_CH
Es ist sowieso langsam fraglich, ob es diese Zürich-eigene Visualisierung noch braucht. Leider liefert der Kanton Zürich keine genauen Zahlen über die einzelnen Fälle mehr...

**Comment by tamberg** [comment]
Vielleicht auf der _CH Seite das _Zürich_ im Titel einfach auf https://rsalzer.github.io/COVID_19_CH/#detail_ZH verlinken? Und auf der _ZH Seite dasselbe als Redirect / Link?

**Comment by rsalzer** [comment]
Ja, oder den Link gleich ganz rausnehmen und dieses Repository löschen :)

**Comment by tamberg** [comment]
Ev. hat's noch jemand gebookmarked.
